### ISSUE TITLE
Notification  don't work  in Android targetSdkVersion 26

### ISSUE THREAD

**Issue by skylarklxlong** [jgilfelt/chuck#93]
android targetSdkVersion = 26
com.readystatesoftware.chuck:library:1.1.0

The notification bar does not display messages

**Comment by Ashok-Varma** [comment]
Hey @skylarklxlong, since app is targeting 26. Notifications must have channels to display. Chuck doesn't have channel specified

This project is no longer maintained. You can try one of these active repos
https://github.com/Ashok-Varma/Gander - Gander
https://github.com/ChuckerTeam/chucker - Chucker

**Comment by skylarklxlong** [comment]
@Ashok-Varma  Thank you for your help
